version: '3.7'

services:
  server:
    build:
      dockerfile: ./.dockerfiles/Dockerfile
      args:
        LOGIN_USER: 'docker'
        WORKSPACE: '/home/docker/.autotesting'
    image: autotest-backend-classic-dev:1.0.0
    volumes:
      - .:/app:cached
      - workspace:/home/docker/.autotesting:rw
    environment:
      - REDIS_URL=redis://redis:6379/
      - WORKSPACE=/home/docker/.autotesting
      - SUPERVISOR_URL=127.0.0.1:9001
      - AUTOTESTER_CONFIG=/app/.dockerfiles/docker-config.yml
    depends_on:
      - redis

  redis: # TODO: only have one redis container for the api and the backend
    image: redis:7.0.4-alpine
    volumes:
      - redis_autotest:/data
    ports:
    - 6379

volumes:
  postgres_autotest:
  redis_autotest:
  workspace:

networks:
  markus_dev:
    name: markus_dev
